schema_version: 1

context:
  name: types-docker
  version: "7.2.0.20260728"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: eeb780deddb000d3be7584cca16b02fc7f68b135b0039977be13c121861db197

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - types-paramiko
    - types-requests
    - urllib3 >=2

tests:
  - python:
      imports:  # dummy import to get pip_check running
        - os
      pip_check: true
      python_version: ${{ python_min }}.*
  - package_contents:
      site_packages:
        - docker-stubs/__init__.pyi

about:
  summary: Typing stubs for docker
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed/tree/main/stubs/docker

extra:
  recipe-maintainers:
    - StevenSchaererQC
