schema_version: 1

context:
  name: types-docker
  version: 7.1.0.20250523

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_docker-${{ version }}.tar.gz
  sha256: fd7a2dbc75cbf58170f2ae9ac31d6e810ead646a5b28c016698edb293d43d60d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - types-requests
    - urllib3 >=2

tests:
  - python:
      imports:  # dummy import to get pip_check running
        - os
      pip_check: true
      python_version: ${{ python_min }}.*
  - package_contents:
      site_packages:
        - docker-stubs/__init__.pyi

about:
  summary: Typing stubs for docker
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed/tree/main/stubs/docker

extra:
  recipe-maintainers:
    - StevenSchaererQC
