schema_version: 1

context:
  name: types-docker
  version: "7.2.0.20261006"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/81/bd/7c46cbb3190622accb6c6aed717083712b0531c6e8ec5f753b7b95cdebe6/types_docker-${{ version }}.tar.gz
  sha256: bd2fc6c302bce7c0caeb06b6e60f7738085fc15f7f5be540b917f6dd33b36619

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - types-paramiko
    - types-requests
    - urllib3 >=2

tests:
  - python:
      imports:  # dummy import to get pip_check running
        - os
      pip_check: true
      python_version: ${{ python_min }}.*
  - package_contents:
      site_packages:
        - docker-stubs/__init__.pyi

about:
  summary: Typing stubs for docker
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed/tree/main/stubs/docker

extra:
  recipe-maintainers:
    - StevenSchaererQC
